export const MyIcons = {
    "shooting": "fa-gun",
    "adventure": "fa-person-running",
    "strategy": "fa-braille",
    "casual": "fa-umbrella-beach",
    "driving": "fa-car",
    "mmorpg": "fa-person",
    "cards": "fa-sim-card",
    "moba": "fa-person",
    "puzzle": "fa-puzzle-piece",
    "music": "fa-music",
    "platform": "fa-person-running",
    "battle-royale": "fa-person",
    "racing": "fa-font-awesome-flag",
    "tile-matching": "fa-list-dots",
    "fun": "fa-face-smile-wink",
    "tower-defense": "fa-tower-observation",
    "typing": "fa-keyboard",
    "sports": "fa-volleyball-ball",
    "rpg": "fa-question",
    "all": "fa-home"
}